<?php /* @var $this Tsg_Request_Block_Get_List*/?>
<?php
$helper = Mage::helper('tsg_request');
$requests = $this->getCollection();
?>
<h1>Requests</h1>
<div>
    <ol>
        <?php foreach ($requests as $request): ?>
            <li>
                <div>
                    <a href="<?php echo $request->getRequestUrl()?>">
                        <?php echo $request->getUrl() ?>
                    </a>
                </div>
            </li>
        <?php endforeach; ?>
    </ol>
</div>

